### ISSUE TITLE
Running on CPUs

### ISSUE THREAD

**Issue by SamuelMarks** [btgraham/SparseConvNet#3]
Dear Prof. Ben Warwick,

Nice work with this project!

I'm curious about running your spatially-sparse convolutional networks in the public cloud. Most public cloud options however don't have GPUs. So I was thinking of porting this to fallback to CPUs when GPUs aren't available.

Would welcome your opinion on this, and any suggestions on how best to approach this.

Thanks,

Samuel

PS: Obviously any decent solution I come up will be offered back in a PR

**Comment by jiho** [comment]
I know this does not answer your question directly, but FYI, I've been running SparseConvNet on Amazon g2 instances (which do have GPUs) with a minor modification of the code (the detention of the GPU does not work). The performance is OK, even from EBS (i.e. networked) drives rather than from the dedicated 80GB SSD dedicated to the instance. So that's a possible cloud-based solution.

**Comment by btgraham** [comment]
Samuel: Hello. As Jean-Olivier say, you can run SparseConvNet on g2 instances. 
I am planning on producing a CPU version. My main motivation for doing that would be to make it easier to distribute trained networks, rather than for training. However, in some cases CPUs might be fast enough for training too. 
If you email me (b.graham@warwick.ac.uk) a few details about what kind of data you would be looking at, I will see if I can help.
Regards
Ben

**Comment by SamuelMarks** [comment]
Great, will be in touch.

And yeah @jiho, g2 is certainly an option I've considered, and there's nothing wrong with it, just that I'd like to be able to run this network on other cloud providers (not all of which support GPUs).

**Comment by btgraham** [comment]
I have hacked SparseConvNet to run on the CPU:
https://github.com/btgraham/SparseConvNet-CPU
Unsurprisingly, the GPU version is quite a lot faster!

**Comment by SamuelMarks** [comment]
Wow, excellent, thanks!
